
cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "crates/core",
    "crates/wasm",
    "crates/arena",
]
resolver="3"

[profile.samply]
inherits = "release"
debug = true

[profile.release]
rustflags = ["-Awarnings"]