[package]
name = "hf-arena"
edition = "2024"
description = "Honing calculator for Lost Ark"
repository = "https://github.com/Kenivia/Honing-Forecast"
license = "AGPL-3.0-or-later"

[dependencies]
csv = "1.4.0"
hf-core = { path = "../core" }
paste = "1.0.15"
rand = "0.9.2"
rayon = "1.11.0"
seq-macro = "0.3.6"
serde = "1.0.228"

[features]
v1=[]
default=["v1"]
