[package]
name = "hf-arena"
edition = "2024"
description = "Honing calculator for Lost Ark"
repository = "https://github.com/Kenivia/Honing-Forecast"
license = "AGPL-3.0-or-later"

[dependencies]
chrono = "0.4.42"
csv = "1.4.0"
hf-core = { path = "../core" }
paste = "1.0.15"
rand = "0.9.2"
rayon = "1.11.0"
seq-macro = "0.3.6"
serde = "1.0.228"
serde_json = "1.0.145"
web-sys = { version = "0.3", features = ["console","Performance","Window"] }
cfg-if = "1.0"
ordered-float = "5.1.0"
priority-queue = "2.7.0"



[features]
v1=[]
v2=[]
v3=[]
v4=[]
v5=[]
v6=[]
v7=[]
v8=[]
v9=[]
v10=[]
v11=[]
v12=[]
v13=[]
v14=[]
v15=[]
v16=[]
v17=[]
v18=[]
v19=[]
v20=[]
v21=[]
v22=[]
v23=[]
v24=[]
v25=[]
v26=[]
v27=[]
v28=[]
v29=[]
v30=[]
v31=[]
v32=[]
v33=[]
v34=[]
v35=[]
default=["v35"]

